kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

nameSuffix: -dev

resources:
  - ../../base/

secretGenerator:
  - name: dockerconfigjson-github-com
    type: "kubernetes.io/dockerconfigjson"
    options:
      disableNameSuffixHash: true
      annotations:
        reflector.v1.k8s.emberstack.com/reflects: default/dockerconfigjson-github-com

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: go-ms-ingress
    path: ingress.yaml
