kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
nameSuffix: -dev
resources:
  - ../../base/
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: go-ms-ingress
    path: ingress.yaml
images:
  - name: ghcr.io/botopsy/go-ms
    newTag: latest
